# Generated by Django 3.1.4 on 2020-12-12 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sous_categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('prix', models.IntegerField()),
                ('short_description', models.TextField(default=None)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='upload/produit/')),
                ('categorie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.categorie')),
                ('sous_categorie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.sous_categorie')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='sous_categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.sous_categorie'),
        ),
    ]
