# Generated by Django 3.1.4 on 2020-12-12 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sous_categorie_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='sous_categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.sous_categorie'),
        ),
    ]
