# Generated by Django 3.1.4 on 2020-12-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201212_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image_2',
            field=models.ImageField(upload_to='upload/produit/'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sous_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.sous_categorie'),
        ),
    ]
