# Generated by Django 3.1.4 on 2020-12-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201214_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
