# Generated by Django 3.1.4 on 2020-12-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201214_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='upload/produit/'),
        ),
    ]
