# Generated by Django 3.1.4 on 2020-12-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='telephone',
            new_name='phone',
        ),
    ]
