# Generated by Django 3.1.4 on 2020-12-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201216_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.produit')),
            ],
        ),
    ]
