# Generated by Django 3.1.4 on 2020-12-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
